/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OHOW (https://sketchfab.com/OHOW)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hotdog-low-poly-food-g06-f1a16ce205724dfa8fb72ff397319f5e
title: Hotdog Low Poly Food G06
*/

import { useGLTF } from "@react-three/drei";
import { ComponentProps } from "react";
import type { Mesh, Material } from "three";

useGLTF.preload("/models/hotdog.glb");

const Hotdog = (props: ComponentProps<"group">) => {
  const { nodes, materials } = useGLTF("/models/hotdog.glb") as unknown as {
    nodes: Record<string, Mesh>;
    materials: Record<string, Material>;
  };

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.0005}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Hotdog_Hotdog_0.geometry}
              material={materials.Hotdog}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

export default Hotdog;
